export default {
    logo: require('../assets/cookit_logo.png'),
    bol: require('../assets/ustensile/bol.png'),
    cuptor_microunde: require('../assets/ustensile/cuptor_microunde.png'),
    mixer : require('../assets/ustensile/mixer.png'),
    oala_pe_foc_inchisa: require('../assets/ustensile/oala_pe_foc_inchisa.png'),
    oala_pe_foc:require('../assets/ustensile/oala_pe_foc.png'),
    razatoare : require('../assets/ustensile/razatoare.png'),
    tel : require('../assets/ustensile/tel.png'),
    tigaie_pe_foc_inchisa: require('../assets/ustensile/tigaie_pe_foc_inchisa.png'),
    tigaie_pe_foc: require('../assets/ustensile/tigaie_pe_foc.png'),
    vas_de_masurat : require('../assets/ustensile/vas_de_masurat.png'),
    waiting_egg: require('../assets/waiting_egg.png'),
    step1:require('../assets/statusEgg/step1.png'),
    step2: require('../assets/statusEgg/step2.png'),
    step3 : require('../assets/statusEgg/step3.png'),
    step4: require('../assets/statusEgg/step4.png'),
    step5 : require('../assets/statusEgg/step5.png'),
    step6 : require('../assets/statusEgg/step6.png'),
    step7 : require('../assets/statusEgg/step7.png'),
    step8 : require('../assets/statusEgg/step8.png'),
    step9 : require('../assets/statusEgg/step9.png'),
    step10 : require('../assets/statusEgg/step10.png'),
    finish : require('../assets/statusEgg/finish.png'),
}