export default [
    {
        id: 1,
        title: "title cook one",
        subtitle: "subtitle cook one",
        image: require('../covers/carbonara.jpg'),
        targetDescriptionScreen: "Presentation",
        targetTutorialScreen: "TutorialOne",
        ingredients: "text aliniat frumos cu ingredeinte",
        ustensile: "text aliniat frumos cu ustensile",
        totalTime:"Timp total de pentru a gati",
         
    } ,
    {
        id: 2,
        title: "title cook two",
        subtitle: "subtitle cook two",
        image: require('../covers/carbonara.jpg'),
        targetDescriptionScreen: "Presentation",
        targetTutorialScreen: "TutorialOne",
        ingredients: "text aliniat frumos cu ingredeinte",
        ustensile: "text aliniat frumos cu ustensile",
        totalTime:"Timp total de pentru a gati",
         
    } ,
    {
        id: 3,
        title: "title cook three",
        subtitle: "subtitle cook three",
        image: require('../covers/carbonara.jpg'),
        targetDescriptionScreen: "Presentation",
        targetTutorialScreen: "TutorialOne",
        ingredients: "text aliniat frumos cu ingredeinte",
        ustensile: "text aliniat frumos cu ustensile",
        totalTime:"Timp total de pentru a gati",
         
    } ,
    {
        id: 4,
        title: "title cook one",
        subtitle: "subtitle cook one",
        image: require('../covers/carbonara.jpg'),
        targetDescriptionScreen: "Presentation",
        targetTutorialScreen: "TutorialOne",
        ingredients: "text aliniat frumos cu ingredeinte",
        ustensile: "text aliniat frumos cu ustensile",
        totalTime:"Timp total pentru a gati",
         
    } ,
    {
        id: 5,
        title: "title cook one",
        subtitle: "subtitle cook one",
        image: require('../covers/carbonara.jpg'),
        targetDescriptionScreen: "Presentation",
        targetTutorialScreen: "TutorialOne",
        ingredients: "text aliniat frumos cu ingredeinte",
        ustensile: "text aliniat frumos cu ustensile",
        totalTime:"Timp total pentru a gati",
         
    } ,
    {
        id: 6,
        title: "title cook one",
        subtitle: "subtitle cook one",
        image: require('../covers/carbonara.jpg'),
        targetDescriptionScreen: "Presentation",
        targetTutorialScreen: "TutorialOne",
        ingredients: "text aliniat frumos cu ingredeinte",
        ustensile: "text aliniat frumos cu ustensile",
        totalTime:"Timp total pentru a gati",
         
    } ,
    {
        id: 7,
        title: "title cook seven",
        subtitle: "subtitle cook seven",
        image: require('../covers/carbonara.jpg'),
        targetDescriptionScreen: "Presentation",
        targetTutorialScreen: "TutorialOne",
        ingredients: "text aliniat frumos cu ingredeinte",
        ustensile: "text aliniat frumos cu ustensile",
        totalTime:"Timp total pentru a gati",
         
    } ,
    {
        id: 8,
        title: "title cook eight",
        subtitle: "subtitle cook eight",
        image: require('../covers/carbonara.jpg'),
        targetDescriptionScreen: "Presentation",
        targetTutorialScreen: "TutorialOne",
        ingredients: "text aliniat frumos cu ingredeinte",
        ustensile: "text aliniat frumos cu ustensile",
        totalTime:"Timp total pentru a gati",
         
    } ,
]